### ISSUE TITLE
async hell

### ISSUE THREAD

**Issue by kootenpv** [h2non/paco#13]
``` python
async def fetch(url):
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as res:
            return res
```
Might I be the first to call this "async hell" lol?

Is there really no other way to do this?

**Comment by tomas-fp** [comment]
You gonna love "async hell" so far than "callback hell", trust me :D

That's is an isolated representative example, but you have multiple alternatives to avoid too nested statements, such as do not use async context managers (but that would make more boilerplate code), reuse the same sessions instead of create/destroying one.

A possible alternative passing the session instance and returning the response, but you should manually close things manually:
```python
async def fetch(url, session):
  return session.get(url)
```
